.TH GTI 6 2013-04-16

.SH NAME
\fBgti\fP \- Humorous typo-based git runner; drives a car over the terminal.

.SH DESCRIPTION
\fBgti\fP is intended to catch accidental typos of 'gti' instead of 'git'. It
displays an animation of a car driving by, and then launches git. Any
parameters or arguments given to \fBgti\fP will be passed through to git.

The car image is derived from the look of an old VW Golf GTI.

.SH ENVIRONMENT
\fBgti\fP respects the GIT environment variable. If GIT is set, its value will
be used to launch git after the animation finishes, instead of searching for
git in your PATH.

.SH SEE ALSO
\fBgit\fP(1), \fBsl\fP(6)

.SH AUTHOR
\fBgti\fP was written by Richard Wossal <richard@r-wos.org>. This manual was
written by Felix Crux <felixc@felixcrux.com> for the Debian project, but may
be used by others under the same terms as \fBgti\fP itself.
